spring.datasource.url=jdbc:postgresql://dpg-d77mtmuuk2gs73arpfpg-a.oregon-postgres.render.com:5432/poll_db_h9so
spring.datasource.username=poll_db_h9so_user
spring.datasource.password=tjXFq7AjOWa675VCm5MtQmOy1WuZWIng

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

